[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deep-translator>=1.11.4",
    "elevenlabs>=2.20.1",
    "openai>=2.6.1",
    "playsound3>=3.2.8",
    "pydub>=0.25.1",
    "requests>=2.32.5",
]
